/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.graphique;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import projet.main.Histogram;
import projet.main.ImagePNG;
import projet.main.ImageView;

/**
 *
 * @author jecobich
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        setLocation(100, 100);
        radioBoutonBinairisation.setEnabled(false);
        boutonInserer.setEnabled(false);
        checkBox.setEnabled(false);
        boutonAnnulationModifs.setEnabled(false);
        boutonSauvegarder.setEnabled(false);
        boutonVideMemoire.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        boutonSauvegarder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textDonneesImage = new javax.swing.JTextField();
        boutonVideMemoire = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        radioBoutonBleu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radioBoutonGris = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        radioBoutonRouge = new javax.swing.JRadioButton();
        boutonSelectionInsertion = new javax.swing.JButton();
        raidioBoutonVert = new javax.swing.JRadioButton();
        boutonInserer = new javax.swing.JButton();
        histgrammeBouton = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        boutonExtraire = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radioBoutonBinairisation = new javax.swing.JRadioButton();
        boutonAnnulationModifs = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        boutonSauvegarder.setText("Sauvegarder");
        boutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSauvegarderActionPerformed(evt);
            }
        });

        jLabel3.setText("Données de l'image :");

        jLabel4.setText("Taille ");

        textDonneesImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDonneesImageActionPerformed(evt);
            }
        });

        boutonVideMemoire.setText("Vider mémoire");
        boutonVideMemoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonVideMemoireActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoutonBleu);
        radioBoutonBleu.setText("Canal Bleu");
        radioBoutonBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoutonBleuActionPerformed(evt);
            }
        });

        jLabel5.setText("Insertion d'une image dans une autre :");

        buttonGroup1.add(radioBoutonGris);
        radioBoutonGris.setText("Canal Gris");
        radioBoutonGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoutonGrisActionPerformed(evt);
            }
        });

        jLabel6.setText("=>");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoutonRouge);
        radioBoutonRouge.setText("Canal Rouge");
        radioBoutonRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoutonRougeActionPerformed(evt);
            }
        });

        boutonSelectionInsertion.setText("Selectionner l'image");
        boutonSelectionInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSelectionInsertionActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidioBoutonVert);
        raidioBoutonVert.setText("Canal Vert");
        raidioBoutonVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidioBoutonVertActionPerformed(evt);
            }
        });

        boutonInserer.setText("Inserer");
        boutonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonInsererActionPerformed(evt);
            }
        });

        histgrammeBouton.setText("Histogramme");
        histgrammeBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histgrammeBoutonActionPerformed(evt);
            }
        });

        checkBox.setText("Utiliser comme image");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        boutonExtraire.setText("Extraire");
        boutonExtraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonExtraireActionPerformed(evt);
            }
        });

        jLabel2.setText("  Seuil (0-255)");

        jLabel7.setText("=>");

        jLabel1.setText("Cannaux de couleur :");

        buttonGroup1.add(radioBoutonBinairisation);
        radioBoutonBinairisation.setText("Binairisation");
        radioBoutonBinairisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoutonBinairisationActionPerformed(evt);
            }
        });

        boutonAnnulationModifs.setText("Annuler les modifications");
        boutonAnnulationModifs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulationModifsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Ouvrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDonneesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(boutonSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(boutonAnnulationModifs)
                        .addGap(46, 46, 46)
                        .addComponent(boutonVideMemoire))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(radioBoutonRouge)
                                            .addGap(74, 74, 74)
                                            .addComponent(histgrammeBouton)
                                            .addGap(9, 9, 9))
                                        .addComponent(radioBoutonGris)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(radioBoutonBinairisation)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1)
                                        .addComponent(raidioBoutonVert)
                                        .addComponent(radioBoutonBleu)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boutonSelectionInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6))
                                            .addComponent(checkBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boutonInserer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boutonExtraire)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDonneesImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonSauvegarder)
                    .addComponent(boutonVideMemoire)
                    .addComponent(boutonAnnulationModifs))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBoutonRouge)
                    .addComponent(histgrammeBouton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raidioBoutonVert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBoutonBleu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBoutonGris)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBoutonBinairisation)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonSelectionInsertion)
                    .addComponent(boutonInserer)
                    .addComponent(boutonExtraire)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox)
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String chemin = "";
        imageBF = null;
        JFileChooser jFileChooser = new JFileChooser(".");
        int retour = jFileChooser.showOpenDialog(null);
        if (retour == JFileChooser.APPROVE_OPTION) {
            chemin = jFileChooser.getSelectedFile().getName();
            this.path = chemin;
        }
        try {
            imageBF = ImageIO.read(new File(chemin));
            imageSave = imageBF;
        } catch (IOException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImagePNG imagePNG = new ImagePNG(imageBF);
        Graphics2D graphic = (Graphics2D) jPanel1.getGraphics();
        graphic.drawImage(imagePNG.createBufferedImage(), 0, 0, this);

        //Chargement des données pour la taille de l'image
        textDonneesImage.setText(imagePNG.getWidth() + "x" + imagePNG.getHeight());

        boutonAnnulationModifs.setEnabled(true);
        boutonSauvegarder.setEnabled(true);
        boutonVideMemoire.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void radioBoutonRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoutonRougeActionPerformed

        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            BufferedImage im = new ImagePNG(imageBF).getRed().createBufferedImage();
            Graphics2D gd = (Graphics2D) jPanel1.getGraphics();
            gd.drawImage(im, 0, 0, this);
            jPanel1.paintComponents(gd);
            imageSave = im;
        }


    }//GEN-LAST:event_radioBoutonRougeActionPerformed

    private void raidioBoutonVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidioBoutonVertActionPerformed

        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            BufferedImage im = new ImagePNG(imageBF).getGreen().createBufferedImage();
            Graphics2D gd = (Graphics2D) jPanel1.getGraphics();
            gd.drawImage(im, 0, 0, this);
            jPanel1.paintComponents(gd);
            imageSave = im;
        }

    }//GEN-LAST:event_raidioBoutonVertActionPerformed

    private void radioBoutonBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoutonBleuActionPerformed

        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            BufferedImage im = new ImagePNG(imageBF).getBlue().createBufferedImage();
            Graphics2D gd = (Graphics2D) jPanel1.getGraphics();
            gd.drawImage(im, 0, 0, this);
            jPanel1.paintComponents(gd);
            imageSave = im;
        }
    }//GEN-LAST:event_radioBoutonBleuActionPerformed

    private void radioBoutonBinairisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoutonBinairisationActionPerformed
        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        }
        if (imageBF != null && jTextField1.getText() == "") {
            JOptionPane.showMessageDialog(null, "Il faut choisir un seuil pour la binairisation");
        }
        if (imageBF != null && jTextField1.getText() != "") {
            ImagePNG imPNG = new ImagePNG(imageBF);
            int valeur = Integer.parseInt(jTextField1.getText());
            Graphics2D gd = (Graphics2D) jPanel1.getGraphics();
            gd.drawImage(imPNG.binairisation(valeur).createBufferedImage(), 0, 0, this);
        }
    }//GEN-LAST:event_radioBoutonBinairisationActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        int valeur = -1; //pour verifer si il y a eu une erreur de conversion en entier et eviter de repeter la meme boite de dialogue
        boolean verif = true;
        try {
            valeur = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            verif = false;
            JOptionPane.showMessageDialog(null, "Il faut saisir un entier entre 0 et 255");
        }
        if ((valeur < 0 || valeur > 255) && verif) {
            JOptionPane.showMessageDialog(null, "Il faut choisir une valeur entre 0 et 255");
        } else if (verif == true) {
            radioBoutonBinairisation.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void radioBoutonGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoutonGrisActionPerformed

        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            BufferedImage im = new ImagePNG(imageBF).getGrey().createBufferedImage();
            Graphics2D gd = (Graphics2D) jPanel1.getGraphics();
            gd.drawImage(im, 0, 0, this);
            jPanel1.paintComponents(gd);
            imageSave = im;
        }
    }//GEN-LAST:event_radioBoutonGrisActionPerformed

    private void boutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSauvegarderActionPerformed
        if (imageSave == null) {
            JOptionPane.showMessageDialog(null, "Ouvrir ou modifier une image pour l'enregistrer");
        } else {
            JFileChooser jFileChooser = new JFileChooser(".");
            int retour = jFileChooser.showSaveDialog(null);
            if (retour == JFileChooser.APPROVE_OPTION) {
                ImagePNG imagePNG = new ImagePNG(imageSave);
                imagePNG.saveImage(jFileChooser.getSelectedFile().getName());
            }
        }

    }//GEN-LAST:event_boutonSauvegarderActionPerformed

    private void textDonneesImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDonneesImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDonneesImageActionPerformed

    private void histgrammeBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histgrammeBoutonActionPerformed
        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            Histogram histogram = new Histogram(new ImagePNG(imageBF));
            histogram.setVisible(true);
        }

    }//GEN-LAST:event_histgrammeBoutonActionPerformed

    private void boutonSelectionInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSelectionInsertionActionPerformed
        if (imageBF == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            File file;
            JFileChooser jFileChooser = new JFileChooser(".");
            int retour = jFileChooser.showOpenDialog(null);
            if (retour == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser.getSelectedFile();
                try {
                    imageInseree = ImageIO.read(file);
                } catch (IOException ex) {
                    Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
                }
                boutonInserer.setEnabled(true);
            }
        }
    }//GEN-LAST:event_boutonSelectionInsertionActionPerformed

    private void boutonVideMemoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonVideMemoireActionPerformed
        jPanel1.removeAll();
        jPanel1.repaint();
        imageBF = null;
        imageSave = null;
        imageInseree = null;
    }//GEN-LAST:event_boutonVideMemoireActionPerformed

    private void boutonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonInsererActionPerformed
        ImagePNG imagePNG1 = new ImagePNG(imageBF);
        ImagePNG imagePNG2 = new ImagePNG(imageInseree);
        ImagePNG insertion = imagePNG1.insertImage(imagePNG2);
        Graphics2D g = (Graphics2D) jPanel1.getGraphics();
        imageSave = insertion.createBufferedImage();
        g.drawImage(imageSave, 0, 0, this);
        jPanel1.paintComponents(g);
        checkBox.setEnabled(true);
    }//GEN-LAST:event_boutonInsererActionPerformed

    private void boutonExtraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonExtraireActionPerformed

        if (imageSave == null) {
            JOptionPane.showMessageDialog(null, MessageChargementImage);
        } else {
            ImagePNG imagePNGInseree = new ImagePNG(imageSave);
            ImageView imageViewInseree = new ImageView("Image inseree",
                    imagePNGInseree.getInseredImage().createBufferedImage());
            imageViewInseree.setVisible(true);
        }

    }//GEN-LAST:event_boutonExtraireActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        if (checkBox.isSelected()) {
            imageBF = imageSave;
            radioBoutonGris.setEnabled(false);
            jTextField1.setEnabled(false);
        } else {
            try {
                imageBF = ImageIO.read(new File(path));
            } catch (IOException ex) {
                Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
            }
            radioBoutonGris.setEnabled(true);
            jTextField1.setEnabled(true);
            boutonExtraire.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    private void boutonAnnulationModifsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulationModifsActionPerformed
        Graphics2D g = (Graphics2D) jPanel1.getGraphics();

        try {
            imageBF = ImageIO.read(new File(path));
            g.drawImage(imageBF, 0, 0, this);
        } catch (IOException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel1.paintComponents(g);
    }//GEN-LAST:event_boutonAnnulationModifsActionPerformed

    private BufferedImage imageBF = null;
    private BufferedImage imageBFSave = null;
    private BufferedImage imageSave = null;
    private BufferedImage imageInseree = null;
    private BufferedImage imageAssemblee = null;
    private String MessageChargementImage = "Il faut charger une image";
    private String path = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnulationModifs;
    private javax.swing.JButton boutonExtraire;
    private javax.swing.JButton boutonInserer;
    private javax.swing.JButton boutonSauvegarder;
    private javax.swing.JButton boutonSelectionInsertion;
    private javax.swing.JButton boutonVideMemoire;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton histgrammeBouton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radioBoutonBinairisation;
    private javax.swing.JRadioButton radioBoutonBleu;
    private javax.swing.JRadioButton radioBoutonGris;
    private javax.swing.JRadioButton radioBoutonRouge;
    private javax.swing.JRadioButton raidioBoutonVert;
    private javax.swing.JTextField textDonneesImage;
    // End of variables declaration//GEN-END:variables
}
